version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --metrics-enabled=true
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-net

  internal-gateway:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: internal_gateway
    ports:
      - "5172:5172"   # HTTP
      - "7161:7161"   # HTTPS
    working_dir: /app
    volumes:
      - ./src/Learning.InternalGateway.Gateway:/app
    command: ["dotnet", "Learning.InternalGateway.Gateway.dll", "--urls", "https://0.0.0.0:7161;http://0.0.0.0:5172"]
    depends_on:
      - keycloak
    networks:
      - keycloak-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data:

networks:
  keycloak-net:
